# ============================================================
# PathGuard — Local HTTP Server
# Reads .env, generates /js/firebase-config.js in memory,
# and serves the full app on http://localhost:3000
# ============================================================

$rootPath = $PSScriptRoot
$envFile  = Join-Path $rootPath ".env"

# ── Read .env ─────────────────────────────────────────────────
$env_vars = @{}
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        $line = $_.Trim()
        if ($line -and $line -notmatch "^#" -and $line -match "=") {
            $parts = $line -split "=", 2
            $env_vars[$parts[0].Trim()] = $parts[1].Trim()
        }
    }
} else {
    Write-Host "  ERROR: .env file not found at $envFile" -ForegroundColor Red
    exit 1
}

$PORT = if ($env_vars["APP_PORT"]) { [int]$env_vars["APP_PORT"] } else { 3000 }

# ── Check Firebase config status ─────────────────────────────
$PROJ_ID   = $env_vars["FIREBASE_PROJECT_ID"]
$API_KEY   = $env_vars["FIREBASE_API_KEY"]
$APP_ID    = $env_vars["FIREBASE_APP_ID"]
$SENDER_ID = $env_vars["FIREBASE_MESSAGING_SENDER_ID"]

$PLACEHOLDER = @("PASTE_YOUR_WEB_API_KEY_HERE","PASTE_YOUR_SENDER_ID_HERE","PASTE_YOUR_APP_ID_HERE","PASTE_API_KEY_HERE","PASTE_SENDER_ID_HERE","PASTE_APP_ID_HERE","YOUR_API_KEY","GET_FROM_CONSOLE","")
$FB_READY = ($API_KEY -and $PLACEHOLDER -notcontains $API_KEY -and
             $APP_ID  -and $PLACEHOLDER -notcontains $APP_ID  -and
             $SENDER_ID -and $PLACEHOLDER -notcontains $SENDER_ID)

# ── Build firebase-config.js (served from memory) ─────────────
$fbConfigJs = @"
// Auto-generated by serve.ps1 from .env — do not edit manually.
// Regenerated on every server start.
window.__PATHGUARD_CONFIG__ = {
  apiKey:            "$($env_vars['FIREBASE_API_KEY'])",
  authDomain:        "$($env_vars['FIREBASE_AUTH_DOMAIN'])",
  projectId:         "$($env_vars['FIREBASE_PROJECT_ID'])",
  storageBucket:     "$($env_vars['FIREBASE_STORAGE_BUCKET'])",
  messagingSenderId: "$($env_vars['FIREBASE_MESSAGING_SENDER_ID'])",
  appId:             "$($env_vars['FIREBASE_APP_ID'])",
  measurementId:     "$($env_vars['FIREBASE_MEASUREMENT_ID'])",
  databaseId:        "$($env_vars['FIREBASE_DATABASE_ID'])"
};
"@
$fbConfigBytes = [System.Text.Encoding]::UTF8.GetBytes($fbConfigJs)

# ── MIME types ─────────────────────────────────────────────────
$mime = @{
  ".html"  = "text/html; charset=utf-8"
  ".css"   = "text/css; charset=utf-8"
  ".js"    = "application/javascript; charset=utf-8"
  ".json"  = "application/json"
  ".png"   = "image/png"
  ".jpg"   = "image/jpeg"
  ".svg"   = "image/svg+xml"
  ".ico"   = "image/x-icon"
  ".woff2" = "font/woff2"
  ".woff"  = "font/woff"
  ".ttf"   = "font/ttf"
}

# ── Start listener ─────────────────────────────────────────────
$http = [System.Net.HttpListener]::new()
$http.Prefixes.Add("http://localhost:$PORT/")
try { $http.Start() } catch {
    Write-Host ""
    Write-Host "  ERROR: Port $PORT is already in use." -ForegroundColor Red
    Write-Host "  Kill the other process, or change APP_PORT in .env" -ForegroundColor Yellow
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}

# ── Banner ─────────────────────────────────────────────────────
Clear-Host
Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║         PathGuard — Local Server             ║" -ForegroundColor Cyan
Write-Host "  ╠══════════════════════════════════════════════╣" -ForegroundColor Cyan
Write-Host "  ║                                              ║" -ForegroundColor Cyan
Write-Host "  ║   URL  :  http://localhost:$PORT                ║" -ForegroundColor Green
Write-Host "  ║   Proj :  $PROJ_ID     ║" -ForegroundColor White

if ($FB_READY) {
    Write-Host "  ║   Firebase: ✓ CONNECTED                      ║" -ForegroundColor Green
} else {
    Write-Host "  ║   Firebase: ⚠ NOT configured                 ║" -ForegroundColor Yellow
    Write-Host "  ║                                              ║" -ForegroundColor Yellow
    Write-Host "  ║   TO CONNECT FIREBASE:                       ║" -ForegroundColor Yellow
    Write-Host "  ║   1. Go to console.firebase.google.com       ║" -ForegroundColor Yellow
    Write-Host "  ║   2. Open project: identity-security-58adc   ║" -ForegroundColor Yellow
    Write-Host "  ║   3. Project Settings → Your apps → Web      ║" -ForegroundColor Yellow
    Write-Host "  ║   4. Copy firebaseConfig values into .env    ║" -ForegroundColor Yellow
    Write-Host "  ║   5. Restart this server                     ║" -ForegroundColor Yellow
    Write-Host "  ║                                              ║" -ForegroundColor Yellow
    Write-Host "  ║   App still works in DEMO mode until then.   ║" -ForegroundColor Cyan
}

Write-Host "  ║                                              ║" -ForegroundColor Cyan
Write-Host "  ║   Ctrl+C to stop                             ║" -ForegroundColor Gray
Write-Host "  ╚══════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

Start-Process "http://localhost:$PORT/home.html"

# ── Request loop ───────────────────────────────────────────────
while ($http.IsListening) {
    $ctx  = $http.GetContext()
    $req  = $ctx.Request
    $resp = $ctx.Response
    try {
        $urlPath = $req.Url.AbsolutePath

        # Serve generated firebase-config.js live from .env
        if ($urlPath -eq "/js/firebase-config.js") {
            $currentEnv = @{}
            if (Test-Path $envFile) {
                Get-Content $envFile | ForEach-Object {
                    $l = $_.Trim()
                    if ($l -and $l -notmatch "^#" -and $l -match "=") {
                        $p = $l -split "=", 2
                        $currentEnv[$p[0].Trim()] = $p[1].Trim()
                    }
                }
            }
            $dynJs = @"
// Auto-generated by serve.ps1 from .env — do not edit manually.
window.__PATHGUARD_CONFIG__ = {
  apiKey:            "$($currentEnv['FIREBASE_API_KEY'])",
  authDomain:        "$($currentEnv['FIREBASE_AUTH_DOMAIN'])",
  projectId:         "$($currentEnv['FIREBASE_PROJECT_ID'])",
  storageBucket:     "$($currentEnv['FIREBASE_STORAGE_BUCKET'])",
  messagingSenderId: "$($currentEnv['FIREBASE_MESSAGING_SENDER_ID'])",
  appId:             "$($currentEnv['FIREBASE_APP_ID'])",
  measurementId:     "$($currentEnv['FIREBASE_MEASUREMENT_ID'])",
  databaseId:        "$($currentEnv['FIREBASE_DATABASE_ID'])"
};
"@
            $dynBytes = [System.Text.Encoding]::UTF8.GetBytes($dynJs)
            $resp.StatusCode      = 200
            $resp.ContentType     = "application/javascript; charset=utf-8"
            $resp.ContentLength64 = $dynBytes.LongLength
            $resp.OutputStream.Write($dynBytes, 0, $dynBytes.Length)
            Write-Host "  200  /js/firebase-config.js  (generated live from .env)" -ForegroundColor DarkGreen
            $resp.OutputStream.Close(); continue
        }

        # Block .env from being served directly
        if ($urlPath -match "\.env") {
            $b = [System.Text.Encoding]::UTF8.GetBytes("403 Forbidden")
            $resp.StatusCode = 403; $resp.ContentType = "text/plain"
            $resp.ContentLength64 = $b.LongLength
            $resp.OutputStream.Write($b, 0, $b.Length)
            $resp.OutputStream.Close(); continue
        }

        # Default root
        if ($urlPath -eq "/" -or $urlPath -eq "") { $urlPath = "/home.html" }

        # Build safe file path
        $rel   = $urlPath.TrimStart("/").Replace("/", [System.IO.Path]::DirectorySeparatorChar)
        $parts = $rel.Split([System.IO.Path]::DirectorySeparatorChar) |
                 Where-Object { $_ -ne ".." -and $_ -ne "." -and $_ -ne "" }
        $fp = $rootPath
        foreach ($p in $parts) { $fp = Join-Path $fp $p }

        if ([System.IO.File]::Exists($fp)) {
            $ext = [System.IO.Path]::GetExtension($fp).ToLower()
            $ct  = if ($mime[$ext]) { $mime[$ext] } else { "application/octet-stream" }
            $d   = [System.IO.File]::ReadAllBytes($fp)
            $resp.StatusCode = 200; $resp.ContentType = $ct; $resp.ContentLength64 = $d.LongLength
            $resp.OutputStream.Write($d, 0, $d.Length)
            Write-Host "  200  $urlPath" -ForegroundColor DarkGray
        } else {
            $b = [System.Text.Encoding]::UTF8.GetBytes("404 Not Found: $urlPath")
            $resp.StatusCode = 404; $resp.ContentType = "text/plain"; $resp.ContentLength64 = $b.LongLength
            $resp.OutputStream.Write($b, 0, $b.Length)
            Write-Host "  404  $urlPath" -ForegroundColor Yellow
        }
    } catch { Write-Host "  ERR  $($_.Exception.Message)" -ForegroundColor Red }
    finally  { try { $resp.OutputStream.Close() } catch {} }
}
$http.Stop()
