module.exports = (req, res) => {
  res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store, max-age=0');
  
  const config = {
    apiKey:            process.env.FIREBASE_API_KEY            || "AIzaSyBJsXHPvHbo1yj20_rCJvcPcUp_9wLYuHM",
    authDomain:        process.env.FIREBASE_AUTH_DOMAIN        || "identity-security-58adc.firebaseapp.com",
    projectId:         process.env.FIREBASE_PROJECT_ID         || "identity-security-58adc",
    storageBucket:     process.env.FIREBASE_STORAGE_BUCKET     || "identity-security-58adc.firebasestorage.app",
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || "905091909481",
    appId:             process.env.FIREBASE_APP_ID             || "1:905091909481:web:f783fd453dc923919d1ff8",
    measurementId:     process.env.FIREBASE_MEASUREMENT_ID     || "G-77S2KQK0L0",
    databaseId:        process.env.FIREBASE_DATABASE_ID        || "indentity"
  };
  
  res.status(200).send(`// Auto-generated by Vercel Serverless Function\nwindow.__PATHGUARD_CONFIG__ = ${JSON.stringify(config, null, 2)};\n`);
};
